### ISSUE TITLE
object-specific methods bound to ogr classes

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/ogr#86]
- [x] Forward some object to the issue/pr/... instances to allow connection to the service. (Classes are not only data-holders.)
- [x] All ogr classes to have properties with setters allowing to update its attributes
    - I can do `my_pr.title = "something"`
- [x] Objects are linked together (Service <-> Project <-> PR <-> PRComment)
- [x] Keep old methods, mark them as deprecated.

needs #121

**Comment by mfocko** [comment]
- [ ] Prepare file structure
- [ ] Comments

**Comment by lachmanfrantisek** [comment]
@mfocko What's needed for the `Release`? Only the setters for properties?

**Comment by mfocko** [comment]
> @mfocko What's needed for the `Release`? Only the setters for properties?

- method to create object from `raw_release`
- fix tests
- looking at the code probably move some things from abstract to base class

**Comment by lachmanfrantisek** [comment]
Thanks for the update
